<div class="page-container" id="modal_act_emp">
    <form class="form_crear_emp" action="act_emp.php" method="POST">
        <div class="card">
            <h1 class="card-header">Crear Empleado</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Cédula de Identidad // 1-2345-6789</span>
                    </div>
                    <input type="text" class="form-control" id="emp_ced_id" name="emp_ced_id" aria-describedby="Cédula de Identidad // 1-2345-6789" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre del Empleado</span>
                    </div>
                    <input type="text" class="form-control" id="emp_nombre" name="emp_nombre" aria-describedby="Nombre del Empleado" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Primer apellido</span>
                    </div>
                    <input type="text" class="form-control" id="emp_apellido1" name="emp_apellido1" aria-describedby="Primer apellido" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Segundo apellido</span>
                    </div>
                    <input type="text" class="form-control" id="emp_apellido2" name="emp_apellido2" aria-describedby="Segundo apellido" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Direccion corta</span>
                    </div>
                    <input type="text" class="form-control" id="emp_direccion" name="emp_direccion" aria-describedby="Direccion corta" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Fecha de Nacimiento</span>
                    </div>
                    <input type="date" class="form-control" id="emp_fecha_nac" name="emp_fecha_nac" aria-describedby="Fecha de Nacimiento" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Fecha de Ingreso</span>
                    </div>
                    <input type="date" class="form-control" id="emp_fecha_ingreso" name="emp_fecha_ingreso" aria-describedby="Fecha de Ingreso" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Salaio del Empleado</span>
                    </div>
                    <input type="number" class="form-control" id="emp_salario" name="emp_salario" min="0" aria-describedby="Salaio del Empleado" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Selecciona un Puesto</label>
                    </div>
                    <select class="custom-select" id="inputGroupSelect01" id="pt_id" name="pt_id" required>
                    <option id="defaultsubCat"  disabled selected><font color="#828282">--Selecciona una Puesto--</font></option>
                        <?php
                        require("conn.php");
                        $result = $conn->query("SELECT DISTINCT puestos_trabajo.pt_nombre_puesto FROM puestos_trabajo INNER JOIN empleados ON puestos_trabajo.pt_id=empleados.pt_id");
                        while($row=mysqli_fetch_array($result)){
                            ?>
                            <option  value="<?php echo $row['pt_nombre_puesto']; ?>" ><?php echo $row['pt_nombre_puesto']; ?></option>
                            <?php mysqli_close($conn);
                        } ?>
                    </select>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Observaciones</span>
                    </div>
                    <textarea id="emp_observaciones" name="emp_observaciones" class="form-control" aria-label="Observaciones"></textarea>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Telefono Principal</span>
                    </div>
                    <input type="text" class="form-control" id="emp_telefono1" name="emp_telefono1" aria-describedby="Telefono Principal" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Telefono Secundario</span>
                    </div>
                    <input type="text" class="form-control" id="emp_telefono2" name="emp_telefono2" aria-describedby="Telefono Secundario">
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Correo</span>
                    </div>
                    <input type="text" class="form-control" id="emp_correo" name="emp_correo" aria-describedby="Correo">
                </div>
            </div>
            <div class="card-footer text-right">
                <a href="#buscar_emp" class="logo btn">
                    <i class="icon ion-md-search"></i> BUSCAR
                </a>
                <input type="submit" class="btn btn-primary" name="" value="ACTUALIZAR">
            </div>
        </div>
    </form>
</div>
