<div class="modal_container" id="modal_crear_emp">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">crear Empleado</span>
    <form class="form_crear_emp" action="crear_emp.php" method="POST">
        <input type="text" name="emp_ced_id" value="" placeholder="Cédula de Identidad // 1-2345-6789"  required>
        <input id='capitalize' type="text" name="emp_nombre" value="" placeholder="Nombre del Empleado" required>
        <input id='capitalize' type="text" name="emp_apellido1" value="" placeholder="Primer apellido" required>
        <input id='capitalize' type="text" name="emp_apellido2" value="" placeholder="Segundo apellido" required>
        <input type="text" name="emp_direccion" value="" placeholder="Direccion corta">
        <a id="a_form" href="#">Fecha de Nacimiento</a>
        <input type="date" name="emp_fecha_nac" value="" placeholder="Fecha de nacimiento" required>
        <a id="a_form" href="#">Fecha de Ingreso</a>
        <input type="date" name="emp_fecha_ingreso" value="" placeholder="Fecha de Ingreso" required>
        <input type="number" name="emp_salario" value="" min="0" placeholder="Salaio del Empleado" required>
        <select class="select" name="pt_id" required>
        <option id="defaultCat"  disabled selected><font color="#828282">--Selecciona una Puesto--</font></option>
        <?php
            require("conn.php");
            $result = $conn->query("SELECT DISTINCT puestos_trabajo.pt_nombre_puesto FROM puestos_trabajo INNER JOIN empleados ON puestos_trabajo.pt_id=empleados.pt_id");
            while($row=mysqli_fetch_array($result)){
                ?>
                <option  value="<?php echo $row['pt_nombre_puesto']; ?>" ><?php echo $row['pt_nombre_puesto']; ?></option>
                <?php mysqli_close($conn);
            } ?>
        </select>
        <textarea name="emp_observaciones" rows="2" placeholder="Observaciones"></textarea>
        <input type="text" name="emp_telefono1" value="" placeholder="Telefono Principal" required>
        <input type="text" name="emp_telefono2" value="" placeholder="Telefono Secundario">
        <input type="email" name="emp_correo" value="" placeholder="Correo">
        <input type="submit" class="btn" name="" value="REGISTRAR">
    </form>
    </div>
</div>