<div class="page-container" id="modal_act_subcat">
    <form class="form_crear_cat" action="act_subcat.php" method="POST">
        <div class="card">
            <h1 class="card-header">Actualizar Sub Categoría</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre de la Sub Categoría</span>
                    </div>
                    <input type="text" class="form-control" id="subCat_nombre" name="subCat_nombre" aria-describedby="Nombre de la Sub Categoría" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre de la Categoría</span>
                    </div>
                    <input type="text" class="form-control" id="cat_nombre" name="cat_nombre" aria-describedby="Nombre de la Categoría" required>
                </div>

                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Descripción</span>
                    </div>
                    <textarea id="subCat_descripcion" name="subCat_descripcion" class="form-control" aria-label="Descripción de la Sub-Categoría"></textarea>
                </div>
                <input type="hidden" id="subCat_id" name="subCat_id" value="" ></input>
            </div>

            <div class="card-footer text-right">
                <a href="#buscar_subcat" class="logo btn">
                    <i class="icon ion-md-search"></i> BUSCAR
                </a>
                <input type="submit" class="btn btn-primary" name="" value="REGISTRAR">
            </div>

        </div>
    </form>
</div>