<div class="page-container" id="modal_act_cat">
    <form class="form_crear_cat" action="act_cat.php" method="POST">
        <div class="card">
            <h1 class="card-header">Actualizar categoría</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre de la Categoría</span>
                    </div>
                    <input type="text" class="form-control" id="cat_nombre_id" name="cat_nombre_id" aria-describedby="Nombre de la Categoría" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre de la Super Categoría</span>
                    </div>
                    <input type="text" class="form-control" id="supCat_nombre" name="supCat_nombre" aria-describedby="Nombre de la Super Categoría" required>
                </div>

                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Descripción</span>
                    </div>
                    <textarea id="cat_descripcion" name="cat_descripcion" class="form-control" aria-label="Descripción"></textarea>
                </div>

                <input type="hidden" id="cat_id" name="cat_id" value="" ></input>
            </div>
            <div class="card-footer text-right">
                <a href="#buscar_cat" class="logo btn">
                    <i class="icon ion-md-search"></i> BUSCAR
                </a>
                <input type="submit" class="btn btn-primary" name="" value="REGISTRAR">
            </div>
        </div>
    </form>
</div>