<div class="modal_container" id="modal_act_subcat">
    <div>
        <a href="index.php" class="close">+</a>
        <span class="modal_heading">Actualizar sub-categoría</span>
        <a href="#buscar_subcat" class="logo">
        <i class="icon ion-md-search"></i>
        </a>
        <form class="form_crear_cat" action="act_subcat.php" method="POST">
        <?php
        require("conn.php");
        if(isset($_GET['subCat_nombre'])){
            $subCat_nombre = $_GET['subCat_nombre'];
            $query = "SELECT * FROM sub_categorias WHERE subCat_nombre = '$subCat_nombre'";
            $result = mysqli_query($conn, $query);
            while($row = mysqli_fetch_array($result)){
            ?>
            <input type="text" id="subCat_nombre" name="subCat_nombre" value="" placeholder="Nombre de la Sub-Categoría" required><?php echo $row['subCat_nombre']; ?></input>
            <input type="text" id="cat_nombre" name="cat_nombre" value="" placeholder="Nombre de la Categoría" required><?php echo $row['cat_id']; ?></input>
            <textarea id="subCat_descripcion" name="subCat_descripcion" rows="3" placeholder="Descripción de la Sub-Categoría"><?php echo $row['subCat_descripcion']; ?></textarea>
            <input type="hidden" id="subCat_id" name="subCat_id" value="" ><?php echo $row['subCat_id']; ?></input>
            <input type="submit" class="btn" name="" value="ACTUALIZAR">
            <?php mysqli_close($conn);
            }
        } else{
            ?>
            <input type="text" id="subCat_nombre" name="subCat_nombre" value="" placeholder="Nombre de la Sub-Categoría" required>
            <input type="text" id="cat_nombre" name="cat_nombre" value="" placeholder="Nombre de la Categoría" required>
            <textarea id="subCat_descripcion" name="subCat_descripcion" rows="3" placeholder="Descripción de la Sub-Categoría"></textarea>
            <input type="hidden" id="subCat_id" name="subCat_id" value="" ></input>
            <input type="submit" class="btn" name="" value="ACTUALIZAR">
            <?php
        }
        ?>
        </form>
    </div>
</div>