<div class="page-container" id="modal_crear_usu">
    <form id="crear_usuario" class="form_crear_emp" action="crear_usuario.php" method="POST">
        <div class="card">
            <h1 class="card-header">Crear Usuario</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Selecciona un Perfil</label>
                    </div>
                    <select class="custom-select" id="inputGroupSelect01" name="per_id" required>
                        <option id="defaultsubCat"  disabled selected><font color="#828282">--Selecciona un Perfil--</font></option>
                        <?php
                        require("conn.php");
                        $result = $conn->query("SELECT DISTINCT per_nombre FROM perfiles");
                        while($row=mysqli_fetch_array($result)){
                        ?>
                        <option  value="<?php echo $row['per_nombre']; ?>" ><?php echo $row['per_nombre']; ?></option>
                        <?php mysqli_close($conn);
                        } ?>
                    </select>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Usuario</span>
                    </div>
                    <input type="text" class="form-control" name="usu_login" aria-describedby="Digite Usuario" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Contraseña</span>
                    </div>
                    <input type="password" class="form-control" id="usu_password" name="usu_password" aria-describedby="Contraseña" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Confirmar Contraseña</span>
                    </div>
                    <input type="password" class="form-control" id="usu_password2" name="usu_password2" aria-describedby="Confirmar Contraseña" required>
                </div>
                <span id='message11'></span>
            </div>
            <div class="card-footer text-right">
                <input type="submit" class="btn btn-primary" name="" value="CREAR">
            </div>
        </div>
    </form>
</div>