<script >
    $('#usu_password, #usu_password2').on('keyup', function () {
    if ($('#usu_password').val() == $('#usu_password2').val()) {
    $('#message11').html('Contraseñas Iguales ✔').css('color', 'green');
    } else
    $('#message11').html('Contraseñas Diferentes ✘').css('color', 'red');
    });
</script>
        <!-- Crear modal para eliminar usuarios-->
<div class="page-container" id="modal_eli_usu">
    <form class="form_crear_emp" action="eli_usu.php" method="POST">
        <div class="card">

            <h1 class="card-header">Eliminar Usuarios</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Selecciona una Usuario</label>
                    </div>
                    <select class="custom-select" id="inputGroupSelect01" name="usu_login" required>
                    <option id="defaultsubCat"  disabled selected><font color="#828282">--Selecciona una Usuario--</font></option>
                        <?php
                        require("conn.php");
                        $result = $conn->query("SELECT DISTINCT usuarios.usu_login FROM perfiles INNER JOIN usuarios ON usuarios.per_id = perfiles.per_id WHERE perfiles.per_id <> 1");
                        while($row=mysqli_fetch_array($result)){
                            ?>
                            <option  value="<?php echo $row['usu_login']; ?>" ><?php echo $row['usu_login']; ?></option>
                            <?php mysqli_close($conn);
                        } ?>
                    </select>
                </div>
            </div>
            <div class="card-footer text-right">
                <input type="submit" class="btn btn-primary" name="" value="ELIMINAR">
            </div>
        </div>
    </form>
</div>