<div class="modal_container" id="modal_act_prov">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">Actualizar proveedores</span>
    <a href="#buscar_prov" class="logo">
        <i class="icon ion-md-search"></i>
    </a>
    <form class="form_crear_cat" action="act_prov.php" method="POST">
        <input type="text" style="background-color: rgba(125,127,125,0.5);" id="prov_nombrecrear" name="prov_nombre" value="" placeholder="Nombre del Proveedor" required readonly>
        <input type="text" id="prov_ced_identidad" name="prov_ced_identidad" value="" placeholder="Cédula Jur./Ident." >
        <input type="text" id="prov_direccion" name="prov_direccion" value="" placeholder="Direccion corta" >
        <input type="text" id="prov_tel1" name="prov_tel1" value="" placeholder="Teléfono 1" >
        <input type="text" id="prov_tel2" name="prov_tel2" value="" placeholder="Teléfono 2" >
        <input type="email" id="prov_correo" name="prov_correo" value="" placeholder="Correo" >
        <input type="hidden" id="prov_id1" name="prov_id" value="">
        <input type="submit" class="btn" name="" value="ACTUALIZAR">
    </form>
    </div>
</div>