<div class="modal_container" id="modal_crear_prov">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">crear proveedores</span>
    <form class="form_crear_cat" action="crear_prov.php" method="POST">
        <input id='capitalize' type="text" name="prov_nombre" value="" placeholder="Nombre del Proveedor" required>
        <input type="text" name="prov_ced_identidad" value="" placeholder="Cédula Jur./Ident." >
        <input id='capitalize' type="text" name="prov_direccion" value="" placeholder="Direccion corta" >
        <input type="text" name="prov_tel1" value="" placeholder="Teléfono 1"  >
        <input type="text" name="prov_tel2" value="" placeholder="Teléfono 2"  >
        <input type="email" name="prov_correo" value="" placeholder="Correo" >
        <input type="submit" class="btn" name="" value="REGISTRAR">
    </form>
    </div>
</div>