<div class="modal_container" id="modal_act_cli">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">Actualizar clientes</span>
    <a href="#buscar_cli" class="logo">
        <i class="icon ion-md-search"></i>
    </a>
    <form class="form_crear_cat" action="act_cliente.php" method="POST">
        <input type="text" style="background-color: rgba(125,127,125,0.5);" id="cli_nombrecrear" name="cli_nombre" value="" placeholder="Nombre del Cliente" required readonly>
        <input type="text" id="cli_ced_identidad" name="cli_ced_identidad" value="" placeholder="Cédula Jur./Ident." >
        <input type="text" id="cli_direccion" name="cli_direccion" value="" placeholder="Direccion corta" >
        <input type="text" id="cli_tel1" name="cli_tel1" value="" placeholder="Teléfono 1" >
        <input type="text" id="cli_tel2" name="cli_tel2" value="" placeholder="Teléfono 2" >
        <input type="email" id="cli_correo" name="cli_correo" value="" placeholder="Correo" >
        <input type="hidden" id="cli_id" name="cli_id" value="">
        <input type="submit" class="btn" name="" value="ACTUALIZAR">
    </form>
    </div>
</div>