<div class="modal_container" id="modal_crear_cli">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">crear clientes</span>
    <form class="form_crear_cat" action="crear_cliente.php" method="POST">
        <input id='capitalize' type="text" name="cli_nombre" value="" placeholder="Nombre del Cliente" required>
        <input type="text" name="cli_ced_identidad" value="" placeholder="Cédula Jur./Ident." >
        <input id='capitalize' type="text" name="cli_direccion" value="" placeholder="Direccion corta" >
        <input type="text" name="cli_tel1" value="" placeholder="Teléfono 1">
        <input type="text" name="cli_tel2" value="" placeholder="Teléfono 2">
        <input type="email" name="cli_correo" value="" placeholder="Correo" >
        <input type="submit" class="btn" name="" value="REGISTRAR">
    </form>
    </div>
</div>