<div class="page-container" id="modal_act_prod">
    <form class="form_crear_prod" action="act_prod.php" method="POST">
        <div class="card">
            <h1 class="card-header">Actualizar Productos</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre del Producto</span>
                    </div>
                    <input type="text" class="form-control" id="prod_nombre" name="prod_nombre" aria-describedby="Nombre del Producto" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre de la Sub-Categoría</span>
                    </div>
                    <input type="text" class="form-control" id="subcat" name="subcat" aria-describedby="Nombre de la Sub-Categoría" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre del Proveedor</span>
                    </div>
                    <input type="text" class="form-control" id="prov_id" name="prov_id" aria-describedby="Nombre del Proveedor" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Código de Stock</span>
                    </div>
                    <input type="text" class="form-control" id="prod_cod_stock" name="prod_cod_stock" aria-describedby="Código de Stock" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Código de Color</span>
                    </div>
                    <input type="text" class="form-control" id="prod_cod_color" name="prod_cod_color" aria-describedby="Código de Color" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Color</span>
                    </div>
                    <input type="text" class="form-control" id="color" name="color" aria-describedby="Color" required>
                </div>

                <input type="hidden" id="prod_id" name="prod_id" value=""></input>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Cantidad</span>
                    </div>
                    <input type="number" min="0" class="form-control" id="prod_inventario_no_talla" name="prod_inventario_no_talla" aria-describedby="Cantidad" required>
                </div>

            </div>
            <div class="card-footer text-right">
                <a href="#buscar_prod" class="logo btn">
                    <i class="icon ion-md-search"></i> BUSCAR
                </a>
                <input type="submit" class="btn btn-primary" name="" value="REGISTRAR">
            </div>




        </div>
    </form>
</div>