<div class="page-container" id="modal_act_stock">
    <form class="form_crear_prod" action="act_prod_stock.php" method="POST">
        <div class="card">
            <h1 class="card-header">Actualizar El Stock de Productos</h1>
            <div class="card-body">
            <?php
            require("conn.php");
            if(isset($_GET['prod_id'])){
                $prod_id = $_GET['prod_idst'];
                $query = "SELECT * FROM productos WHERE prod_id = '$prod_id'";
                $result = mysqli_query($conn, $query);
                while($row = mysqli_fetch_array($result)){
                ?>
                <input type="hidden" id="prod_idst" name="prod_id" value=""></input>
                <?php mysqli_close($conn);
                }
            } else{
                ?>
                <input type="text" style="background-color: rgba(125,127,125,0.5);" id="prod_nombrest" name="prod_nombre" value="" placeholder="Nombre del Producto" required readonly></input>
                <input type="text" style="background-color: rgba(125,127,125,0.5);" id="subcatst" name="subcat" value="" placeholder="Nombre de la Sub-Categoría" required readonly></input>
                <input type="hidden" id="prov_idst" name="prov_nombre" value="" placeholder="Nombre del Proveedor" required></input>
                <input type="hidden" id="prod_cod_stockst" name="prod_cod_stock" value="" placeholder="Código de Stock"></input>
                <input type="hidden" id="prod_cod_colorst" name="prod_cod_color" value="" placeholder="Código de Color"></input>
                <input type="text" style="background-color: rgba(125,127,125,0.5);" id="colorst" name="color" value="" placeholder="Color" readonly></input>
                <input type="hidden" id="prod_idst" name="prod_id" value=""></input>
                <input type="hidden" id="subCat_id_idst" name="subCat_id" value=""></input>
                <input type="hidden" id="prov_idst" name="prov_id" value=""></input>
                <input type="hidden" id="prod_inventario_no_tallast" name="prod_inventario_no_talla" value="" placeholder="Cantidad -- solo MATERIA PRIMA"></input>
                <a href="#" class="textospequenosforms"><b>VERIFIQUE LA TALLA Y GENERO</b></a><br>
                <select class="select" id="tallasprod22" name="talla_id" required></select> <!-- aqui va el javascrip-->
                <select class="select" id="genero22" name="prod_talla_genero" required></select> <!-- aqui va el javascrip-->
                <input type="text" id="" name="Op_num" value="">OP Asociada</input>
                <a href="#" class="textospequenosforms"><b>NO usar signos de suma ni resta</b></a><br>
                <label for="stocksumar">Cantidad a sumar : </label><input type="number" min="0" id="stocksumar" name="stocksumar" value=""></input><br>
                <label for="stockrestar">Cantidad a restar : </label><input type=" number" min="0" id="stockrestar" name="stockrestar" value=""></input>
                <input type="submit" class="btn" name="" value="ACTUALIZAR">
                <?php
            }
            ?>
            </div>
        </div>
    </form>
</div>