<div class="modal_container" id="modal_act_maq">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">Actualizar maquiladores</span>
    <a href="#buscar_maq" class="logo">
        <i class="icon ion-md-search"></i>
    </a>
    <form class="form_crear_cat" action="act_maq.php" method="POST">
        <input type="text" style="background-color: rgba(125,127,125,0.5);" id="maq_nombrecrear" name="maq_nombre" value="" placeholder="Nombre del Maquilador" required>
        <input type="text" id="maq_ced_identidad" name="maq_ced_identidad" value="" placeholder="Cédula Jur./Ident." >
        <input type="text" id="maq_direccion" name="maq_direccion" value="" placeholder="Direccion corta" >
        <input type="text" id="tel" name="maq_tel1" value="" placeholder="Teléfono 1">
        <input type="text" id="tel" name="maq_tel2" value="" placeholder="Teléfono 2">
        <input type="email" id="maq_correo" name="maq_correo" value="" placeholder="Correo" >
        <textarea name="maq_que_maquila" id="maq_que_maquila" rows="3" placeholder="Qué tipo de prendas maquila?"></textarea>
        <input type="hidden" id="maq_id" name="maq_id" value="">
        <input type="submit" class="btn" name="" value="ACTUALIZAR">
    </form>
    </div>
</div>