<div class="page-container" id="modal_act_maq">
    <form class="form_crear_cat" action="act_maq.php" method="POST">

        <div class="card">

            <h1 class="card-header">Actualizar Maquiladores</h1>
            <div class="card-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Nombre del Maquilador</span>
                    </div>
                    <input type="text" class="form-control" id="maq_nombrecrear" name="maq_nombre" aria-describedby="Nombre del Maquilador" required readonly>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Cédula Jur./Ident.</span>
                    </div>
                    <input type="text" class="form-control" id="maq_ced_identidad" name="maq_ced_identidad" aria-describedby="Cédula Jur./Ident." required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Direccion corta</span>
                    </div>
                    <input type="text" class="form-control" id="maq_direccion" name="maq_direccion" aria-describedby="Direccion corta" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Teléfono 1</span>
                    </div>
                    <input type="text" class="form-control" id="maq_tel1" name="maq_tel1" aria-describedby="Teléfono 1" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Teléfono 2</span>
                    </div>
                    <input type="text" class="form-control" id="maq_tel2" name="maq_tel2" aria-describedby="Teléfono 2" required>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">Correo</span>
                    </div>
                    <input type="text" class="form-control" id="maq_correo" name="maq_correo" aria-describedby="Correo" required>
                </div>

                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Qué tipo de prendas maquila?</span>
                    </div>
                    <textarea name="maq_que_maquila" class="form-control" aria-label="Qué tipo de prendas maquila?"></textarea>
                </div>
                <input type="hidden" id="maq_id" name="maq_id" value="">
            </div>
            <div class="card-footer text-right">
                <a href="#buscar_maq" class="logo">
                    <i class="icon ion-md-search"></i> BUSCAR
                </a>
                <input type="submit" class="btn btn-primary" name="" value="REGISTRAR">
            </div>
        </div>
    </form>
</div>
