<div class="modal_container" id="modal_crear_maq">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">crear Maquiladores</span>
    <form class="form_crear_cat" action="crear_maq.php" method="POST">
        <input id='capitalize' type="text" name="maq_nombre" value="" placeholder="Nombre del Maquilador" required>
        <input type="text" name="maq_ced_identidad" value="" placeholder="Cédula Jur./Ident." >
        <input id='capitalize' type="text" name="maq_direccion" value="" placeholder="Direccion corta" >
        <input type="text" name="maq_tel1" value="" placeholder="Teléfono 1" >
        <input type="text" name="maq_tel2" value="" placeholder="Teléfono 2" >
        <input type="email" name="maq_correo" value="" placeholder="Correo" >
        <textarea name="maq_que_maquila" rows="3" placeholder="Qué tipo de prendas maquila?"></textarea>
        <input type="submit" class="btn" name="" value="REGISTRAR">
    </form>
    </div>
</div>