<div class="modal_container" id="modal_crear_pt">
    <div>
    <a href="index.php" class="close">+</a>
    <span class="modal_heading">crear puesto de trabajo</span>
    <form class="form_crear_cat" action="crear_pt.php" method="POST">
        <input id='capitalize' type="text" name="pt_nombre" value="" placeholder="Nombre del Puesto" required>
        <textarea name="pt_descripcion" rows="3" placeholder="Descripción del puesto"></textarea>
        <input type="submit" class="btn" name="" value="REGISTRAR">
    </form>
    </div>
</div>